# Generated by Django 4.0.4 on 2022-08-22 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique', max_length=255, unique=True, verbose_name='Category name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Product category unique URL')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product for store', max_length=255, verbose_name='Product')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Product unique URL')),
                ('is_active', models.BooleanField(default=True, help_text='Change product visibility', verbose_name='Product visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Update at')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required, unique', max_length=255, unique=True, verbose_name='Subtype name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Product sub type unique URL')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required, unique', max_length=255, unique=True, verbose_name='Product type name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Product type unique URL')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_store.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubTypeSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='Name')),
                ('productsubtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_store.productsubtype')),
            ],
            options={
                'verbose_name': 'Specification for product',
                'verbose_name_plural': 'specifications for product',
            },
        ),
        migrations.AddField(
            model_name='productsubtype',
            name='producttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_store.producttype'),
        ),
        migrations.CreateModel(
            name='ProductSpecificationFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Product specification value (255 words)', max_length=255, verbose_name='Value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_store.product')),
                ('productspecification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_store.productsubtypespecification')),
            ],
            options={
                'verbose_name': 'Product cpecification value',
                'verbose_name_plural': 'Product cpecification values',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='product-images/default.png', help_text='Upload product image', upload_to='product-images/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, help_text='Please add alternative text', max_length=255, null=True, verbose_name='Alternative text for image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_store.product')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='productsubtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_store.productsubtype'),
        ),
    ]
