# Generated by Django 4.0.4 on 2022-05-26 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Youtube_To_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.URLField()),
                ('file_path', models.CharField(max_length=255, verbose_name='Путь к файлу')),
                ('only_audio', models.BooleanField(default=False, verbose_name='Только аудио дорожка')),
            ],
            options={
                'verbose_name': 'Конвертация ютуб ссылки в видео-файл',
                'verbose_name_plural': 'Конвертация ютуб ссылки в видео-файл',
            },
        ),
        migrations.CreateModel(
            name='FileConvertationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_for_convertation', models.FileField(upload_to='temporary_files/Video/%Y/%m/%d', verbose_name='Файл для конвертации')),
                ('file_converted', models.FileField(upload_to='temporary_files/Video/%Y/%m/%d', verbose_name='Файл конвертированный')),
                ('to_which_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='converter_site.categoryvideo', verbose_name='В какой тип надо преобразовать видео-файл')),
            ],
        ),
        migrations.CreateModel(
            name='FileConvertationPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_for_convertation', models.FileField(upload_to='temporary_files/Picture/%Y/%m/%d', verbose_name='Файл для конвертации')),
                ('file_converted', models.FileField(upload_to='temporary_files/Picture/%Y/%m/%d', verbose_name='Файл конвертированный')),
                ('to_which_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='converter_site.categorypicture', verbose_name='В какой тип надо преобразовать picture-файл')),
            ],
        ),
        migrations.CreateModel(
            name='FileConvertationAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_for_convertation', models.FileField(upload_to='temporary_files/Audio/%Y/%m/%d', verbose_name='Файл для конвертации')),
                ('file_converted', models.FileField(upload_to='temporary_files/Audio/%Y/%m/%d', verbose_name='Файл конвертированный')),
                ('to_which_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='converter_site.categoryaudio', verbose_name='В какой тип надо преобразовать аудио-файл')),
            ],
        ),
    ]
