# Generated by Django 4.0.4 on 2022-08-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileconvertationaudio',
            name='file_converted',
            field=models.FileField(upload_to='temporary_files/Audio/%Y/%m/%d', verbose_name='Converted file'),
        ),
        migrations.AlterField(
            model_name='fileconvertationaudio',
            name='file_for_convertation',
            field=models.FileField(upload_to='temporary_files/Audio/%Y/%m/%d', verbose_name='File for convertation'),
        ),
        migrations.AlterField(
            model_name='fileconvertationaudio',
            name='to_which_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='converter_site.categoryaudio', verbose_name='To which type need convert file'),
        ),
        migrations.AlterField(
            model_name='fileconvertationpicture',
            name='file_converted',
            field=models.FileField(upload_to='temporary_files/Picture/%Y/%m/%d', verbose_name='Converted file'),
        ),
        migrations.AlterField(
            model_name='fileconvertationpicture',
            name='file_for_convertation',
            field=models.FileField(upload_to='temporary_files/Picture/%Y/%m/%d', verbose_name='File for convertation'),
        ),
        migrations.AlterField(
            model_name='fileconvertationpicture',
            name='to_which_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='converter_site.categorypicture', verbose_name='To which type need convert file'),
        ),
        migrations.AlterField(
            model_name='fileconvertationvideo',
            name='file_converted',
            field=models.FileField(upload_to='temporary_files/Video/%Y/%m/%d', verbose_name='Converted file'),
        ),
        migrations.AlterField(
            model_name='fileconvertationvideo',
            name='file_for_convertation',
            field=models.FileField(upload_to='temporary_files/Video/%Y/%m/%d', verbose_name='File for convertation'),
        ),
        migrations.AlterField(
            model_name='fileconvertationvideo',
            name='to_which_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='converter_site.categoryvideo', verbose_name='To which type need convert file'),
        ),
    ]
